on: push

jobs:
  homework-node:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - run: echo "HOMEWORK"
      - uses: actions/checkout@v3
      - name: Install MySQL
        run: |
          sudo apt-get update && sudo apt-get install -y mysql-client
      - name: MySQL version (client)
        run: mysql --version
      - name: MySQL query
        run: |
          sleep 5
          mysql -h 127.0.0.1 -u root -proot -e 'SELECT VERSION();'
