on: push
jobs:
  homework-node:
    runs-on: ubuntu-latest
    container: mysql
    steps:
    - run: echo "HOMEWORK"
    - run: mysql --version
    - uses: actions/checkout@v3
    - run: mysql -e 'SELECT VERSION();'